// Laser-cut sheet parts for the machine — flat DXFs cut from plywood.
//
// Unlike the 3D printed parts these don't go through the slicer pipeline;
// the DXFs live in static/dxf/ and their SVG previews are generated by
// slicer/dxf_preview.py (re-run it when a DXF changes).

export type LaserCutPart = {
	id: string;
	name: string;
	assembly?: string; // grouping label, e.g. the two cage pieces
	description: string;
	// expected stock thickness, quoted both ways since sheets are sold in imperial
	// but cut/modeled in metric (nearest full mm)
	thicknessIn: string; // e.g. '3/8″'
	thicknessMm: number; // nearest full-mm equivalent
	widthMm: number; // bounding box of the cut, from dxf_preview.py
	heightMm: number;
	qty: number; // per machine
	onshape: string; // pinned OnShape version this DXF was exported from
	dxf: string; // download path
	preview: string; // SVG outline preview path
	updated: string; // date of the DXF export (ISO)
};

export const LASER_CUT_PARTS: LaserCutPart[] = [
	{
		id: 'cable-cage-top',
		name: 'Cable Cage Top',
		assembly: 'Cable Cage',
		description:
			'Top plate of the cable cage. Has a keyed cutout for easy insertion/removal of the interface.',
		thicknessIn: '1/8″',
		thicknessMm: 3,
		widthMm: 325,
		heightMm: 375,
		qty: 1,
		onshape:
			'https://cad.onshape.com/documents/36d65973fe08f685f790dc8b/v/3b8fafc8cab54b09332e14d2/e/80730ec6cc50aab029fb5397',
		dxf: '/dxf/cable-cage-top.dxf',
		preview: '/dxf-previews/cable-cage-top.svg',
		updated: '2026-07-10'
	},
	{
		id: 'cable-cage-bottom',
		name: 'Cable Cage Bottom',
		assembly: 'Cable Cage',
		description: 'Bottom plate of the cable cage.',
		thicknessIn: '1/8″',
		thicknessMm: 3,
		widthMm: 325,
		heightMm: 375,
		qty: 1,
		onshape:
			'https://cad.onshape.com/documents/36d65973fe08f685f790dc8b/v/3b8fafc8cab54b09332e14d2/e/5faa32cf4604f648fd981991',
		dxf: '/dxf/cable-cage-bottom.dxf',
		preview: '/dxf-previews/cable-cage-bottom.svg',
		updated: '2026-07-10'
	},
	{
		id: 'top-plate',
		name: 'Top plate',
		description:
			'Machine top plate. Has 5 cable holes and holes for the main stepper. Does not yet have mount holes for the C-channels.',
		thicknessIn: '3/8″',
		thicknessMm: 10,
		widthMm: 672,
		heightMm: 770,
		qty: 1,
		onshape:
			'https://cad.onshape.com/documents/36d65973fe08f685f790dc8b/v/3b8fafc8cab54b09332e14d2/e/e6605a6f604d25617d91b7bc',
		dxf: '/dxf/top-plate.dxf',
		preview: '/dxf-previews/top-plate.svg',
		updated: '2026-07-10'
	}
];
